### ISSUE TITLE
Is this action published?

### ISSUE THREAD

**Issue by roryabraham** [actions-ecosystem/action-get-merged-pull-request#142]
## What you want to add
Hi 👋  Is this action published on the Github actions marketplace yet? I'd like to start using it but it doesn't seem like it's published yet.

## Why this is needed
This repo solves a problem that I have in the CI/CD flow I'm building out. I can create a duplicate action in my repo, but I'd prefer to just use this one 😄

**Comment by micnncim** [comment]
Hi @roryabraham, sorry for the inconvenience. I've republished this action: https://github.com/marketplace/actions/actions-ecosystem-action-get-merged-pull-request. Hope it'd be helpful for you.
